name = "umarote-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"


[[d1_databases]]
binding = "DB"
database_name = "umarote-db"
database_id = "local"
preview_database_id = "local"
migrations_dir = "src/db/migrations"

[env.development]
[[env.development.d1_databases]]
binding = "DB"
database_name = "umarote-db"
database_id = "local"
preview_database_id = "local"