CREATE TABLE `horses` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`birth_year` integer NOT NULL,
	`sex` text NOT NULL,
	`color` text NOT NULL,
	`father` text NOT NULL,
	`mother` text NOT NULL,
	`trainer` text NOT NULL,
	`owner` text NOT NULL,
	`breeder` text NOT NULL,
	`earnings` real DEFAULT 0 NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `race_entries` (
	`id` text PRIMARY KEY NOT NULL,
	`race_id` text NOT NULL,
	`horse_id` text NOT NULL,
	`frame_no` integer NOT NULL,
	`horse_no` integer NOT NULL,
	`age` integer NOT NULL,
	`jockey` text NOT NULL,
	`weight` real NOT NULL,
	`trainer` text NOT NULL,
	`affiliation` text NOT NULL,
	`popularity` integer,
	`body_weight` integer,
	`body_weight_diff` integer,
	`blinkers` integer DEFAULT false,
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`race_id`) REFERENCES `races`(`race_id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`horse_id`) REFERENCES `horses`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `race_results` (
	`id` text PRIMARY KEY NOT NULL,
	`race_id` text NOT NULL,
	`horse_id` text NOT NULL,
	`date` text NOT NULL,
	`race_name` text NOT NULL,
	`venue` text NOT NULL,
	`course_type` text NOT NULL,
	`distance` integer NOT NULL,
	`direction` text NOT NULL,
	`course_conf` text,
	`weather` text,
	`course_condition` text NOT NULL,
	`cushion_value` real,
	`finish_position` integer NOT NULL,
	`jockey` text NOT NULL,
	`weight` real NOT NULL,
	`time` text NOT NULL,
	`margin` text NOT NULL,
	`pos2c` integer,
	`pos3c` integer,
	`pos4c` integer,
	`average_position` real NOT NULL,
	`last_three_furlong` text NOT NULL,
	`odds` real NOT NULL,
	`popularity` integer NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`race_id`) REFERENCES `races`(`race_id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`horse_id`) REFERENCES `horses`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `races` (
	`race_id` text PRIMARY KEY NOT NULL,
	`date` text NOT NULL,
	`venue` text NOT NULL,
	`race_no` integer NOT NULL,
	`race_name` text NOT NULL,
	`class_name` text NOT NULL,
	`surface` text NOT NULL,
	`distance` integer NOT NULL,
	`direction` text NOT NULL,
	`course_conf` text,
	`track_cond` text NOT NULL,
	`cushion_value` real,
	`field_size` integer,
	`off_at` text,
	`grade` text,
	`win5` integer DEFAULT false,
	`status` text DEFAULT '発売中' NOT NULL,
	`weather` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP
);
