CREATE TABLE `training_records` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`training_type` text NOT NULL,
	`facility` text NOT NULL,
	`training_date` text NOT NULL,
	`weekday` text NOT NULL,
	`training_time` text NOT NULL,
	`horse_name` text NOT NULL,
	`class_code` text,
	`sex` text NOT NULL,
	`age` integer NOT NULL,
	`trainer` text NOT NULL,
	`time_10f` real,
	`time_9f` real,
	`time_8f` real,
	`time_7f` real,
	`time_6f` real,
	`time_5f` real,
	`time_4f` real,
	`time_3f` real,
	`time_2f` real,
	`time_1f` real,
	`lap_9` real,
	`lap_8` real,
	`lap_7` real,
	`lap_6` real,
	`lap_5` real,
	`lap_4` real,
	`lap_3` real,
	`lap_2` real,
	`lap_1` real,
	`registration_number` text,
	`affiliation` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP
);
